version: '3'
volumes:
  maas-csa-data:
networks:
  maas-csa:
services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nub3l1U2019!
    volumes:
      # Data volume
      - maas-csa-data:/var/lib/mariadb/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - maas-csa

  maas-csa-frontend:
    image: nginx:alpine
    restart: always
    volumes:
      # Site
      - ./maas-csa:/usr/share/nginx/html/
      # Reverse proxy configuration
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - maas-csa
    depends_on:
      - app

  app:
    build: ./app
    restart: always
    volumes:
      # Application
      - ./app:/app
    working_dir: /app
    networks:
      - maas-csa
    depends_on:
      - db